name: Website Availability Check

on:
  schedule:
    - cron: "0 0 * * *"  # Vérification toutes les 24 heures
  workflow_dispatch: 

jobs:
  check-websites:
    runs-on: ubuntu-latest
    steps:
      - name: Define URLS
        run: |
          echo "URLS=https://selenite.live https://wiki.selenite.live https://auth.selenite.live https://weare.selenite.live https://download.selenite.live" >> $GITHUB_ENV

      - name: Curl websites and response check status code
        run: |
          for url in $URLS; do
            STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" "$url")
            SITE_NAME=$(echo $url | sed 's/https:\/\///' | sed 's/\//-/g')

            if [ "$STATUS_CODE" -eq 200 ]; then
              echo "✅ $url is up"
              echo "DEPLOY_STATE_$SITE_NAME=success" >> $GITHUB_ENV
              echo "DEPLOY_DESC_$SITE_NAME=Up and running" >> $GITHUB_ENV
            else
              echo "❌ $url is down (Status: $STATUS_CODE)"
              echo "DEPLOY_STATE_$SITE_NAME=failure" >> $GITHUB_ENV
              echo "DEPLOY_DESC_$SITE_NAME=Down and not responding (Status: $STATUS_CODE)" >> $GITHUB_ENV
            fi
          done

      - name: Create and Update GitHub Deployment Status
        run: |
          for url in $URLS; do
            SITE_NAME=$(echo $url | sed 's/https:\/\///' | sed 's/\//-/g')
            STATE=$(eval echo \$DEPLOY_STATE_$SITE_NAME)
            DESCRIPTION=$(eval echo \$DEPLOY_DESC_$SITE_NAME)

            DEPLOYMENT_ID=$(curl -s -X POST "https://api.github.com/repos/${{ github.repository }}/deployments" \
              -H "Authorization: token ${{ secrets.SELENITE_PAT }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{
                "ref": "${{ github.ref }}",
                "environment": "'"$SITE_NAME"'",
                "description": "'"$DESCRIPTION"'",
                "auto_merge": false,
                "required_contexts": [],
                "transient_environment": false
              }' | jq -r '.id')

            echo "Deploy ID: $DEPLOYMENT_ID for $SITE_NAME"

            curl -X POST "https://api.github.com/repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses" \
              -H "Authorization: token ${{ secrets.SELENITE_PAT }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{
                "state": "'"$STATE"'",
                "description": "'"$DESCRIPTION"'",
                "environment": "'"$SITE_NAME"'",
                "log_url": "'"$url"'"
              }'
          done