name: Websites Availability Check

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check-websites:
    runs-on: ubuntu-latest
    steps:
      - name: Define the list of websites to check
        run: |
          echo "URLS=https://selenite.live https://wiki.selenite.live https://auth.selenite.live https://weare.selenite.live https://download.selenite.live" >> $GITHUB_ENV

      - name: Curl websites and store the response status code
        run: |
          for url in $URLS; do
            STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" "$url")
            SITE_NAME=$(echo $url | sed 's/https:\/\///' | sed 's/\//-/g')

            if [ "$STATUS_CODE" -eq 200 ]; then
              echo "✅ $SITE_NAME is up and running"
              echo "DEPLOY_STATE_$SITE_NAME=success" >> $GITHUB_ENV
            else
              echo "❌ $SITE_NAME is down"
              echo "DEPLOY_STATE_$SITE_NAME=failure" >> $GITHUB_ENV
            fi
          done

      - name: Create Deployment for each website
        run: |
          for url in $URLS; do
            SITE_NAME=$(echo $url | sed 's/https:\/\///' | sed 's/\//-/g')
            DEPLOY_STATE=$(echo $DEPLOY_STATE_$SITE_NAME)

            DEPLOYMENT_ID=$(curl -s -X POST "https://api.github.com/repos/${{ github.repository }}/deployments" \
              -H "Authorization: token ${{ secrets.SELENITE_PAT }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{
                "ref": "${{ github.ref }}",
                "environment": "'"$SITE_NAME"'",
                "description": "Deploying to '"$SITE_NAME"'",
                "auto_merge": false,
                "required_contexts": [],
                "transient_environment": false
              }' | jq -r '.id')

              echo "DEPLOYMENT_ID_$SITE_NAME=$DEPLOYMENT_ID" >> $GITHUB_ENV

              echo "➡️ Creating deployment for $SITE_NAME with ID $DEPLOYMENT_ID"
          done

      - name: Update Deployment Status for each website
        run: |
          for url in $URLS; do
            SITE_NAME=$(echo $url | sed 's/https:\/\///' | sed 's/\//-/g')
            DEPLOYMENT_ID=$(echo $DEPLOYMENT_ID_$SITE_NAME)

            DEPLOY_STATE=$(echo $DEPLOY_STATE_$SITE_NAME)

            DESCRIPTION="Deployment status for $SITE_NAME is $DEPLOY_STATE"

            curl -s -X POST "https://api.github.com/repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/statuses" \
              -H "Authorization: token ${{ secrets.SELENITE_PAT }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{
                "environment": "'"$SITE_NAME"'",
                "state": "'"$DEPLOY_STATE"'",
                "description": "'"$DESCRIPTION"'",
                "log_url": "'$url'"
              }'

            echo "🚀 Deployment status for $SITE_NAME is $DEPLOY_STATE"
          done