name: Run ESLint on pull requests

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - development
      - production

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node.js @latest
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Check for ESLint errors
        run: |
          if [ $? -ne 0 ]; then
            echo "ESLint found errors. Failing the build."
            exit 1
          fi
