name: Run ESLint on pull requests

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - development
      - production

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install Node.js @latest
        uses: actions/setup-node@v2
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Check for ESLint errors
        run: |
          if [ $? -ne 0 ]; then
            echo "ESLint found errors. Failing the build."
            exit 1
          fi